import { 
  UserSession, 
  Condominium, 
  Asset, 
  WorkOrder, 
  InventoryItem, 
  NormativeCompliance, 
  FinancialRecord, 
  AuditLog,
  ReliabilityKPIs
} from '@/types/maintenance';

export const INITIAL_USERS: UserSession[] = [
  {
    id: 'user-admin',
    name: 'Eng. Príncipe Adam (He-Man)',
    email: 'heman@grayskull.eternia.br',
    role: 'ADMIN',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    title: 'Defensor de Eternia & Diretor de Engenharia Master',
    phone: '(11) 98888-1983',
  },
  {
    id: 'user-gestor',
    name: 'Teela (Capitã da Guarda Real)',
    email: 'teela@palacio.eternia.br',
    role: 'GESTOR',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    title: 'Gestora Geral de Operações & Facilities de Eternia',
    phone: '(11) 97777-1983',
  },
  {
    id: 'user-tecnico',
    name: 'Duncan / Mentor (Man-At-Arms)',
    email: 'duncan.mentor@grayskull.eternia.br',
    role: 'TECNICO',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    title: 'Mestre em Tecnologia, Telemetria & Manutenção 4.0',
    phone: '(11) 96666-1983',
  },
  {
    id: 'user-cliente',
    name: 'Rei Randor (Síndico Geral)',
    email: 'rei.randor@palacio.eternia.br',
    role: 'CLIENTE',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    condominiumId: 'condo-palacio-real',
    title: 'Síndico Geral - Palácio Real & Castelo de Grayskull',
    phone: '(11) 95555-1983',
  }
];

export const INITIAL_CONDOMINIUMS: Condominium[] = [
  {
    id: 'condo-grayskull',
    name: 'Condomínio Fortaleza Castelo de Grayskull',
    cnpj: '77.777.777/0001-88',
    address: 'Planalto Místico dos Segredos, Km 0 - Floresta Perene',
    city: 'Eternia Central',
    state: 'ET',
    towers: 2,
    unitsCount: 120,
    managerName: 'Feiticeira / Sorceress (Síndica Guardiã)',
    managerPhone: '(11) 98888-7777',
    managerEmail: 'sorceress@grayskull.eternia.br',
    avcbExpiry: '2026-11-20',
    pmocStatus: 'CONFORME',
    potabilityExpiry: '2026-10-15',
    spdaExpiry: '2027-02-10',
    totalAssets: 64,
    healthScore: 98,
  },
  {
    id: 'condo-palacio-real',
    name: 'Condomínio Residencial Palácio Real de Eternia',
    cnpj: '10.101.101/0001-00',
    address: 'Alameda da Coroa Real, 1000 - Centro Imperial',
    city: 'Eternia Capital',
    state: 'ET',
    towers: 4,
    unitsCount: 240,
    managerName: 'Rei Randor & Rainha Marlena',
    managerPhone: '(11) 95555-1983',
    managerEmail: 'sindico@palacio.eternia.br',
    avcbExpiry: '2026-12-05',
    pmocStatus: 'CONFORME',
    potabilityExpiry: '2026-09-30',
    spdaExpiry: '2026-11-14',
    totalAssets: 92,
    healthScore: 95,
  },
  {
    id: 'condo-snake-mountain',
    name: 'Complexo Comercial Montanha da Serpente (Snake Mountain)',
    cnpj: '66.666.666/0001-99',
    address: 'Avenida do Hemisfério Sombrio, 666 - Zona das Rochas',
    city: 'Subúrbio Sombrio',
    state: 'ET',
    towers: 3,
    unitsCount: 180,
    managerName: 'Esqueleto / Skeletor & Maligna (Evil-Lyn)',
    managerPhone: '(11) 96666-0000',
    managerEmail: 'esqueleto@snakemountain.eternia.br',
    avcbExpiry: '2026-09-18',
    pmocStatus: 'EM_REVISAO',
    potabilityExpiry: '2026-09-12',
    spdaExpiry: '2026-10-01',
    totalAssets: 58,
    healthScore: 82,
  },
  {
    id: 'condo-fright-zone',
    name: 'Condomínio Industrial Zona do Terror (Hordak Towers)',
    cnpj: '88.888.888/0001-44',
    address: 'Rodovia da Força Horda, Lote 42 - Zona Industrial',
    city: 'Etheria Norte',
    state: 'ET',
    towers: 1,
    unitsCount: 80,
    managerName: 'Lorde Hordak & Sombria',
    managerPhone: '(11) 94444-8888',
    managerEmail: 'hordak@frightzone.eternia.br',
    avcbExpiry: '2026-10-25',
    pmocStatus: 'CONFORME',
    potabilityExpiry: '2026-11-05',
    spdaExpiry: '2027-01-15',
    totalAssets: 76,
    healthScore: 89,
  }
];

export const INITIAL_ASSETS: Asset[] = [
  {
    id: 'asset-chiller-01',
    code: 'CLI-CHL-001',
    name: 'Chiller Criogênico Trane 350 TR (Torre dos Segredos - Grayskull)',
    category: 'CLIMATIZACAO',
    condominiumId: 'condo-grayskull',
    location: 'Cobertura - Barrilete Místico de Grayskull',
    floorLevel: 'COBERTURA',
    brand: 'Trane',
    model: 'RTHD Water-Cooled 350TR',
    serialNumber: 'TRN-2024-8849',
    installDate: '2024-03-15',
    status: 'OPERANDO',
    qrCode: 'ZX360-CLI-CHL-001-CONDO-GJ',
    lastMaintenance: '2026-08-15',
    nextMaintenance: '2026-09-15',
    normativeRef: 'PMOC Lei 13.589/18 / Anvisa RE 09',
    specifications: {
      'Capacidade': '350 TR (1.230 kW)',
      'Fluido Refrigerante': 'R-134a (Ecológico)',
      'Tensão Operação': '380V Trifásico 60Hz',
      'Vazão de Água Gelada': '240 m³/h',
    },
    sensors: [
      {
        id: 'sens-chiller-temp',
        assetId: 'asset-chiller-01',
        type: 'TEMPERATURA',
        label: 'Temp. Saída Água Gelada',
        value: 6.8,
        unit: '°C',
        minThreshold: 4.0,
        maxThreshold: 9.5,
        status: 'NORMAL',
        lastUpdate: 'Há 12 segundos',
        history: [
          { timestamp: '17:00', value: 6.7 },
          { timestamp: '17:15', value: 6.9 },
          { timestamp: '17:30', value: 6.8 },
          { timestamp: '17:45', value: 6.8 }
        ]
      },
      {
        id: 'sens-chiller-vib',
        assetId: 'asset-chiller-01',
        type: 'VIBRACAO',
        label: 'Vibração RMS Mancal',
        value: 1.85,
        unit: 'mm/s',
        minThreshold: 0.0,
        maxThreshold: 4.5,
        status: 'NORMAL',
        lastUpdate: 'Há 12 segundos',
        history: [
          { timestamp: '17:00', value: 1.82 },
          { timestamp: '17:15', value: 1.88 },
          { timestamp: '17:30', value: 1.84 },
          { timestamp: '17:45', value: 1.85 }
        ]
      },
      {
        id: 'sens-chiller-hori',
        assetId: 'asset-chiller-01',
        type: 'HORIMETRO',
        label: 'Horímetro Acumulado',
        value: 4820,
        unit: 'h',
        minThreshold: 0,
        maxThreshold: 10000,
        status: 'NORMAL',
        lastUpdate: 'Há 12 segundos',
        history: [{ timestamp: 'Hoje', value: 4820 }]
      }
    ]
  },
  {
    id: 'asset-bomba-recalque-01',
    code: 'HID-BMB-001',
    name: 'Conjunto Moto-Bomba de Recalque 01 (15 CV - Poço de Grayskull)',
    category: 'HIDRAULICA',
    condominiumId: 'condo-grayskull',
    location: 'Subsolo 2 - Casa de Bombas e Drenagem do Fosso',
    floorLevel: 'SUBSOLO_2',
    brand: 'Schneider / Motores Duncan 4.0',
    model: 'ME-2 150 (Multi-Estágio)',
    serialNumber: 'SCH-9941-B1',
    installDate: '2023-11-10',
    status: 'ALERTA',
    qrCode: 'ZX360-HID-BMB-001-CONDO-GS',
    lastMaintenance: '2026-08-01',
    nextMaintenance: '2026-09-01',
    normativeRef: 'NBR 5626 / NBR 13714',
    specifications: {
      'Potência': '15 CV (11 kW)',
      'Pressão Manométrica': '8.2 bar',
      'Vazão Nominal': '32 m³/h',
      'Selo Mecânico': 'Viton/Silício Duncan',
    },
    sensors: [
      {
        id: 'sens-bmb-pressao',
        assetId: 'asset-bomba-recalque-01',
        type: 'PRESSAO',
        label: 'Pressão de Recalque',
        value: 7.9,
        unit: 'bar',
        minThreshold: 6.5,
        maxThreshold: 9.0,
        status: 'NORMAL',
        lastUpdate: 'Há 5 segundos',
        history: [
          { timestamp: '17:00', value: 7.8 },
          { timestamp: '17:15', value: 8.1 },
          { timestamp: '17:30', value: 7.9 },
          { timestamp: '17:45', value: 7.9 }
        ]
      },
      {
        id: 'sens-bmb-vib',
        assetId: 'asset-bomba-recalque-01',
        type: 'VIBRACAO',
        label: 'Vibração RMS Rotor',
        value: 4.82,
        unit: 'mm/s',
        minThreshold: 0.0,
        maxThreshold: 4.5,
        status: 'WARNING',
        lastUpdate: 'Há 5 segundos',
        history: [
          { timestamp: '17:00', value: 3.2 },
          { timestamp: '17:15', value: 3.9 },
          { timestamp: '17:30', value: 4.5 },
          { timestamp: '17:45', value: 4.82 }
        ]
      },
      {
        id: 'sens-bmb-temp',
        assetId: 'asset-bomba-recalque-01',
        type: 'TEMPERATURA',
        label: 'Temp. Carcaça Motor',
        value: 68.4,
        unit: '°C',
        minThreshold: 20.0,
        maxThreshold: 75.0,
        status: 'NORMAL',
        lastUpdate: 'Há 5 segundos',
        history: [
          { timestamp: '17:00', value: 61.2 },
          { timestamp: '17:15', value: 64.0 },
          { timestamp: '17:30', value: 66.8 },
          { timestamp: '17:45', value: 68.4 }
        ]
      }
    ]
  },
  {
    id: 'asset-gerador-01',
    code: 'ELE-GER-001',
    name: 'Grupo Gerador a Diesel & Plasma Stemac 500 kVA (Emergência Grayskull)',
    category: 'GERADORES',
    condominiumId: 'condo-grayskull',
    location: 'Subsolo 1 - Sala do Gerador & QTA Havoc Shield',
    floorLevel: 'SUBSOLO_1',
    brand: 'Stemac / Cummins Especial Eternia',
    model: 'GSTA-500 Silenciado',
    serialNumber: 'STM-2022-5501',
    installDate: '2022-06-20',
    status: 'OPERANDO',
    qrCode: 'ZX360-ELE-GER-001-CONDO-GS',
    lastMaintenance: '2026-08-20',
    nextMaintenance: '2026-09-20',
    normativeRef: 'NBR 14664 / NBR 5410 / NR-10',
    specifications: {
      'Potência Standby': '500 kVA (400 kW)',
      'Motor': 'Cummins 6 Cilindros Turbo',
      'QTA': 'Automático com comutação em 6.4s',
      'Tanque de Diesel': '500 Litros',
    },
    sensors: [
      {
        id: 'sens-ger-temp',
        assetId: 'asset-gerador-01',
        type: 'TEMPERATURA',
        label: 'Temp. Bloco Motor',
        value: 42.0,
        unit: '°C',
        minThreshold: 30.0,
        maxThreshold: 90.0,
        status: 'NORMAL',
        lastUpdate: 'Há 1 minuto',
        history: [{ timestamp: '17:00', value: 42.0 }]
      },
      {
        id: 'sens-ger-hori',
        assetId: 'asset-gerador-01',
        type: 'HORIMETRO',
        label: 'Horímetro Acumulado',
        value: 348,
        unit: 'h',
        minThreshold: 0,
        maxThreshold: 5000,
        status: 'NORMAL',
        lastUpdate: 'Há 1 minuto',
        history: [{ timestamp: 'Hoje', value: 348 }]
      }
    ]
  },
  {
    id: 'asset-elevador-t1-social',
    code: 'ELV-SOC-001',
    name: 'Elevador Social Torre Real (Schindler 5500 Regenerativo 2.5 m/s)',
    category: 'ELEVADORES',
    condominiumId: 'condo-palacio-real',
    location: 'Casa de Máquinas - Torre Real de Eternia',
    floorLevel: 'COBERTURA',
    brand: 'Atlas Schindler / Duncan Specs',
    model: 'Schindler 5500 (2.5 m/s)',
    serialNumber: 'AS-8832-T1',
    installDate: '2021-09-10',
    status: 'OPERANDO',
    qrCode: 'ZX360-ELV-SOC-001-CONDO-PR',
    lastMaintenance: '2026-08-10',
    nextMaintenance: '2026-09-10',
    normativeRef: 'NBR 16042 / NBR NM 207 / RIA Anual',
    specifications: {
      'Carga': '1000 kg (13 passageiros)',
      'Velocidade': '2.5 m/s',
      'Paradas': '28 andares',
      'Freios de Segurança': 'Bi-direcional com microchaves',
    },
    sensors: [
      {
        id: 'sens-elv-temp',
        assetId: 'asset-elevador-t1-social',
        type: 'TEMPERATURA',
        label: 'Temp. Máquina de Tração',
        value: 38.5,
        unit: '°C',
        minThreshold: 15.0,
        maxThreshold: 65.0,
        status: 'NORMAL',
        lastUpdate: 'Há 2 minutos',
        history: [{ timestamp: '17:00', value: 38.5 }]
      }
    ]
  },
  {
    id: 'asset-bomba-incendio-01',
    code: 'INC-BMB-001',
    name: 'Bomba Principal de Incêndio & AVCB (Sistema Chama Real 30 CV)',
    category: 'INCENDIO_AVCB',
    condominiumId: 'condo-grayskull',
    location: 'Subsolo 2 - Casa de Bombas Anti-Incêndio',
    floorLevel: 'SUBSOLO_2',
    brand: 'Imbil / Guarda Real de Eternia',
    model: 'BE 65-200 (Motor Elétrico 30 CV)',
    serialNumber: 'IMB-INC-2023',
    installDate: '2023-05-18',
    status: 'OPERANDO',
    qrCode: 'ZX360-INC-BMB-001-CONDO-GS',
    lastMaintenance: '2026-08-05',
    nextMaintenance: '2026-09-05',
    normativeRef: 'NBR 13714 / NBR 12693 / Instrução Técnica CB',
    specifications: {
      'Pressão de Teste': '11.5 bar',
      'Vazão': '75 m³/h a 100 mca',
      'Painel de Comando': 'Partida Direta Automática por Pressostato',
    },
    sensors: [
      {
        id: 'sens-inc-pressao',
        assetId: 'asset-bomba-incendio-01',
        type: 'PRESSAO',
        label: 'Pressão da Rede de Hidrantes',
        value: 9.8,
        unit: 'bar',
        minThreshold: 8.5,
        maxThreshold: 12.0,
        status: 'NORMAL',
        lastUpdate: 'Há 30 segundos',
        history: [{ timestamp: '17:00', value: 9.8 }]
      }
    ]
  },
  {
    id: 'asset-reservatorio-sup',
    code: 'HID-RES-001',
    name: 'Reservatório Superior de Água Potável Fonte da Vida (50.000 L)',
    category: 'HIDRAULICA',
    condominiumId: 'condo-grayskull',
    location: 'Cobertura - Barrilete Superior do Castelo',
    floorLevel: 'COBERTURA',
    brand: 'Estrutura Concreto Impermeabilizado Grayskull',
    model: 'Célula Dupla (25.000L + 25.000L)',
    serialNumber: 'RES-SUP-GS-01',
    installDate: '2020-01-01',
    status: 'OPERANDO',
    qrCode: 'ZX360-HID-RES-001-CONDO-GS',
    lastMaintenance: '2026-04-15',
    nextMaintenance: '2026-10-15',
    normativeRef: 'Portaria GM/MS 888/2021 / NBR 5626 (Limpeza Semestral)',
    specifications: {
      'Volume Total': '50.000 Litros',
      'Reserva de Incêndio': '15.000 Litros (Tubulação Afogada)',
      'Última Higienização': '15/04/2026 (Laudo Microbiológico Feiticeira Aprovado)',
    },
    sensors: [
      {
        id: 'sens-res-nivel',
        assetId: 'asset-reservatorio-sup',
        type: 'NIVEL_AGUA',
        label: 'Nível Volumétrico',
        value: 84.5,
        unit: '%',
        minThreshold: 30.0,
        maxThreshold: 98.0,
        status: 'NORMAL',
        lastUpdate: 'Há 10 segundos',
        history: [
          { timestamp: '17:00', value: 78.0 },
          { timestamp: '17:15', value: 82.0 },
          { timestamp: '17:30', value: 85.0 },
          { timestamp: '17:45', value: 84.5 }
        ]
      }
    ]
  }
];

export const INITIAL_WORK_ORDERS: WorkOrder[] = [
  {
    id: 'wo-001',
    code: 'OS-2026-089',
    title: 'Manutenção Preditiva & Substituição de Rolamento - Moto-Bomba de Grayskull 01',
    description: 'Sensor IoT acusou elevação de vibração RMS (4.82 mm/s > 4.5 mm/s) no mancal dianteiro. Duncan / Mentor em campo para desacoplamento, inspeção do alinhamento a laser e troca do rolamento SKF 6308 de Eternium.',
    condominiumId: 'condo-grayskull',
    assetId: 'asset-bomba-recalque-01',
    category: 'HIDRAULICA',
    priority: 'ALTA',
    status: 'EM_ANDAMENTO',
    type: 'CORRETIVA_EMERGENCIAL',
    assignedTechId: 'user-tecnico',
    assignedTechName: 'Duncan / Mentor (Man-At-Arms)',
    scheduledDate: '2026-09-01',
    startedAt: '2026-09-01T16:30:00Z',
    checklist: [
      {
        id: 'chk-1',
        title: 'Bloqueio e Etiquetagem (LOTO / NR-10)',
        description: 'Desenergizar o disjuntor geral da bomba no QDF e aplicar cadeado de segurança com tag.',
        normativeRef: 'NR-10 Segurança em Eletricidade',
        required: true,
        checked: true,
        measuredValue: '0 V verificado',
      },
      {
        id: 'chk-2',
        title: 'Medição de Vibração e Temperatura Prévia',
        description: 'Registrar valor com acelerômetro na carcaça do motor antes do reparo.',
        normativeRef: 'ISO 10816-3',
        required: true,
        checked: true,
        measuredValue: '4.82 mm/s RMS',
      },
      {
        id: 'chk-3',
        title: 'Substituição do Rolamento Dianteiro de Eternium',
        description: 'Instalar rolamento novo com aquecedor indutivo para evitar danos ao eixo.',
        normativeRef: 'NBR 5674',
        required: true,
        checked: false,
      },
      {
        id: 'chk-4',
        title: 'Verificação do Selo Mecânico e Estanqueidade',
        description: 'Inspecionar faces de carbeto de silício e anéis O-Ring.',
        normativeRef: 'NBR 5626',
        required: true,
        checked: false,
      },
      {
        id: 'chk-5',
        title: 'Alinhamento a Laser dos Acoplamentos',
        description: 'Garantir desvio angular e paralelo menor que 0.05 mm.',
        normativeRef: 'Manutenção Preditiva 4.0',
        required: true,
        checked: false,
      }
    ],
    partsUsed: [
      {
        partId: 'part-rolamento-skf',
        partName: 'Rolamento SKF 6308 2RS C3 de Eternium Reforçado',
        quantity: 1,
        unitCost: 145.0,
      }
    ],
    totalCost: 145.0,
    aiDiagnostic: {
      probableCause: 'Fadiga precoce de pista externa por micro-desalinhamento angular com elevação de vibração harmônica.',
      suggestedParts: ['Rolamento SKF 6308 2RS de Eternium', 'Graxa Policarbamida Klüber', 'Selo Mecânico Viton 1.1/4" Duncan'],
      safetyRequirements: ['Desenergização prévia (NR-10)', 'Uso de Óculos e Luva Vaqueta (NR-06)', 'Calço mecânico na tubulação'],
      estimatedHours: 2.5,
      recommendedActions: [
        'Executar LOTO no painel de comando',
        'Substituir rolamento com prensagem uniforme',
        'Realinhar eixo com relógio comparador ou alinhador laser',
        'Coletar assinatura da Feiticeira / Síndico ao término do teste hidrostático'
      ]
    },
    normativeTags: ['NR-10', 'NBR 5626', 'NBR 5674']
  },
  {
    id: 'wo-002',
    code: 'OS-2026-088',
    title: 'Inspeção & Limpeza PMOC Semestral do Chiller Criogênico Trane',
    description: 'Execução do cronograma legal PMOC (Lei 13.589/18). Higienização química das serpentinas, teste de pressostatos e coleta para laudo microbiológico na Torre de Grayskull.',
    condominiumId: 'condo-grayskull',
    assetId: 'asset-chiller-01',
    category: 'CLIMATIZACAO',
    priority: 'MEDIA',
    status: 'AGENDADA',
    type: 'PREVENTIVA_PMOC',
    assignedTechId: 'user-tecnico',
    assignedTechName: 'Duncan / Mentor (Man-At-Arms)',
    scheduledDate: '2026-09-03',
    checklist: [
      {
        id: 'chk-pmoc-1',
        title: 'Inspeção e Lavagem de Filtros G4/F7 de Eternia',
        description: 'Substituição das mantas filtrantes saturadas conforme Anvisa RE 09.',
        normativeRef: 'Lei 13.589/2018 / Portaria MS 3.523',
        required: true,
        checked: false,
      },
      {
        id: 'chk-pmoc-2',
        title: 'Desinfecção de Bandejas e Dreno de Condensado',
        description: 'Aplicação de bactericida biodegradável para evitar colônias de fungos/Legionella.',
        normativeRef: 'Anvisa RE 09',
        required: true,
        checked: false,
      },
      {
        id: 'chk-pmoc-3',
        title: 'Medição de Superaquecimento e Sub-resfriamento',
        description: 'Conectar manifold digital nos pontos de alta e baixa pressão.',
        normativeRef: 'Boas Práticas Refrigeração',
        required: true,
        checked: false,
      }
    ],
    partsUsed: [
      {
        partId: 'part-filtro-manta-g4',
        partName: 'Manta Filtrante Sintética G4 de Fibra de Eternia',
        quantity: 4,
        unitCost: 38.0,
      }
    ],
    totalCost: 152.0,
    normativeTags: ['PMOC', 'Lei 13.589/18', 'Anvisa RE 09']
  },
  {
    id: 'wo-003',
    code: 'OS-2026-085',
    title: 'Teste Mensal de Partida sob Carga do Gerador Stemac (NBR 14664)',
    description: 'Acionamento automático do grupo gerador a diesel & plasma sob carga do QTA Havoc Shield, verificação de tensão de bateria e teste de comutação dos disjuntores motorizados.',
    condominiumId: 'condo-grayskull',
    assetId: 'asset-gerador-01',
    category: 'GERADORES',
    priority: 'MEDIA',
    status: 'CONCLUIDA',
    type: 'PREVENTIVA_PMOC',
    assignedTechId: 'user-tecnico',
    assignedTechName: 'Duncan / Mentor (Man-At-Arms)',
    scheduledDate: '2026-08-20',
    completedAt: '2026-08-20T15:40:00Z',
    checklist: [
      {
        id: 'chk-ger-1',
        title: 'Verificação do Nível de Óleo Lubrificante e Líquido de Arrefecimento',
        description: 'Inspecionar vareta do cárter e nível no vaso de expansão do radiador.',
        normativeRef: 'NBR 14664',
        required: true,
        checked: true,
        measuredValue: 'Nível 100% OK',
      },
      {
        id: 'chk-ger-2',
        title: 'Teste de Tensão e Densidade das Baterias de Partida',
        description: 'Medir tensão em repouso e durante a manivela de partida.',
        normativeRef: 'NR-10',
        required: true,
        checked: true,
        measuredValue: '26.8 V (2x 12V em série)',
      },
      {
        id: 'chk-ger-3',
        title: 'Tempo de Comutação QTA (Simulação Falha Concessionária)',
        description: 'Cronometrar tempo entre o corte e assunção da carga pelos circuitos de emergência.',
        normativeRef: 'NBR 5410',
        required: true,
        checked: true,
        measuredValue: '6.4 segundos',
      }
    ],
    signature: {
      name: 'Rei Randor (Síndico Geral)',
      document: 'CPF: 123.456.789-00',
      role: 'Síndico Geral de Eternia',
      dataUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="200" height="60"><path d="M10 40 Q50 10 100 35 T190 30" stroke="%2338bdf8" stroke-width="2" fill="none"/></svg>',
      timestamp: '20/08/2026 15:40',
      gpsCoordinates: '-23.5701, -46.6542 (Castelo de Grayskull)'
    },
    partsUsed: [],
    totalCost: 0,
    normativeTags: ['NBR 14664', 'NR-10', 'QTA']
  },
  {
    id: 'wo-004',
    code: 'OS-2026-090',
    title: 'Chamado do Síndico: Infiltração no Fosso da Montanha da Serpente',
    description: 'Síndico Esqueleto abriu chamado urgente através do Portal do Cliente relatando gotejamento de água turva sobre o duto de ventilação no Subsolo 2.',
    condominiumId: 'condo-snake-mountain',
    category: 'HIDRAULICA',
    priority: 'CRITICA',
    status: 'ABERTA',
    type: 'SOLICITACAO_MORADOR',
    scheduledDate: '2026-09-02',
    checklist: [
      {
        id: 'chk-inf-1',
        title: 'Identificação da Prumada Afetada',
        description: 'Mapear tubulação de PVC série reforçada ou ferro fundido.',
        normativeRef: 'NBR 5626 / NBR 10844',
        required: true,
        checked: false,
      },
      {
        id: 'chk-inf-2',
        title: 'Reparo com Luva de Correr ou Termofusão',
        description: 'Estancar vazamento e aplicar vedação.',
        normativeRef: 'NBR 5674',
        required: true,
        checked: false,
      }
    ],
    partsUsed: [],
    totalCost: 0,
    normativeTags: ['NBR 10844', 'Garantia Estrutural']
  },
  {
    id: 'wo-005',
    code: 'OS-2026-091',
    title: 'Inspeção Semestral de Portas Corta-Fogo e Iluminação de Emergência AVCB no Palácio Real',
    description: 'Teste de fechamento automático das 56 portas corta-fogo (NBR 11742) e teste de autonomia de 2h do bloco central de baterias de emergência (NBR 10898) no Palácio de Eternia.',
    condominiumId: 'condo-palacio-real',
    category: 'INCENDIO_AVCB',
    priority: 'ALTA',
    status: 'AGUARDANDO_APROVACAO',
    type: 'INSPECAO_NORMATIVA',
    assignedTechId: 'user-tecnico',
    assignedTechName: 'Duncan / Mentor (Man-At-Arms)',
    scheduledDate: '2026-09-04',
    checklist: [
      {
        id: 'chk-pcf-1',
        title: 'Teste de Trinco e Mola das Portas Corta-Fogo',
        description: 'Garantir fechamento estanque a 45 graus.',
        normativeRef: 'NBR 11742',
        required: true,
        checked: true,
        measuredValue: '54 de 56 Conformadas (2 molas reguladas)',
      },
      {
        id: 'chk-pcf-2',
        title: 'Teste de Autonomia das Luminárias de Emergência',
        description: 'Simular corte geral e monitorar por 120 minutos.',
        normativeRef: 'NBR 10898',
        required: true,
        checked: true,
        measuredValue: '135 minutos de autonomia',
      }
    ],
    partsUsed: [],
    totalCost: 0,
    normativeTags: ['AVCB', 'NBR 11742', 'NBR 10898']
  }
];

export const INITIAL_NORMATIVES: NormativeCompliance[] = [
  {
    id: 'norm-pmoc-01',
    condominiumId: 'condo-grayskull',
    normType: 'PMOC',
    title: 'Plano de Manutenção, Operação e Controle (PMOC)',
    code: 'Lei Federal 13.589/2018 / Portaria MS 3.523/1998',
    legalBasis: 'Obrigatório para todos os edifícios de uso público e coletivo com sistema de climatização.',
    validityDate: '2026-12-31',
    status: 'CONFORME',
    certNumber: 'PMOC-2026-ET-8821',
    artNumber: 'ART-CREAET-2026-099412',
    responsibleEngineer: 'Eng. Duncan / Mentor (Man-At-Arms)',
    creaRrt: 'CREA-ET 5069812440',
    inspectionFrequency: 'MENSAL',
    lastInspection: '2026-08-15',
    nextInspection: '2026-09-15',
  },
  {
    id: 'norm-avcb-01',
    condominiumId: 'condo-grayskull',
    normType: 'AVCB',
    title: 'Auto de Vistoria do Corpo de Bombeiros (AVCB Real)',
    code: 'Decreto Estadual ET 63.911 / NBR 13714 / NBR 12693',
    legalBasis: 'Certificação do Corpo de Bombeiros Militar atestando segurança contra incêndio e pânico.',
    validityDate: '2026-11-20',
    status: 'CONFORME',
    certNumber: 'AVCB-CBMET-2023-44109',
    artNumber: 'ART-CBMET-99881',
    responsibleEngineer: 'Major Res. Eng. Stratos (Guarda Real)',
    creaRrt: 'CREA-ET 0601994411',
    inspectionFrequency: 'ANUAL',
    lastInspection: '2025-11-20',
    nextInspection: '2026-11-20',
  },
  {
    id: 'norm-spda-01',
    condominiumId: 'condo-grayskull',
    normType: 'SPDA_NBR5419',
    title: 'Laudo de SPDA & Continuidade Ôhmica de Para-Raios de Eternia',
    code: 'NBR 5419:2015 (Partes 1 a 4) / NR-10',
    legalBasis: 'Verificação da malha de captação Franklyn/Gaiola de Faraday, descidas e aterramento.',
    validityDate: '2027-02-10',
    status: 'CONFORME',
    certNumber: 'LAUDO-SPDA-2026-GS',
    artNumber: 'ART-SPDA-440192',
    responsibleEngineer: 'Eng. Eletricista Roboto (Tecnologia 4.0)',
    creaRrt: 'CREA-ET 5078129001',
    inspectionFrequency: 'ANUAL',
    lastInspection: '2026-02-10',
    nextInspection: '2027-02-10',
  },
  {
    id: 'norm-agua-01',
    condominiumId: 'condo-grayskull',
    normType: 'POTABILIDADE_AGUA',
    title: 'Certificado de Higienização de Caixas d\'Água e Potabilidade Fonte da Vida',
    code: 'Portaria GM/MS 888/2021 / NBR 5626',
    legalBasis: 'Higienização semestral obrigatória dos reservatórios com análise bacteriológica (E. coli, coliformes totais, cloro livre e turbidez).',
    validityDate: '2026-10-15',
    status: 'CONFORME',
    certNumber: 'LAB-AGUA-2026-771',
    responsibleEngineer: 'Biol. e Química Feiticeira / Sorceress',
    creaRrt: 'CRQ-IV 0429188',
    inspectionFrequency: 'SEMESTRAL',
    lastInspection: '2026-04-15',
    nextInspection: '2026-10-15',
  },
  {
    id: 'norm-elev-01',
    condominiumId: 'condo-palacio-real',
    normType: 'ELEVADOR_RIA',
    title: 'Relatório de Inspeção Anual dos Elevadores (RIA) do Palácio',
    code: 'NBR 16042 / Lei Municipal 10.348/1987 (SEGUR)',
    legalBasis: 'Vistoria anual e emissão de ART de responsabilidade técnica de conservação de transporte vertical.',
    validityDate: '2026-10-01',
    status: 'CONFORME',
    certNumber: 'RIA-CONTRU-2025-992',
    artNumber: 'ART-ELEV-2025-0019',
    responsibleEngineer: 'Eng. Mecânico Duncan / Mentor',
    creaRrt: 'CREA-ET 060449102',
    inspectionFrequency: 'ANUAL',
    lastInspection: '2025-10-01',
    nextInspection: '2026-10-01',
  },
  {
    id: 'norm-gas-01',
    condominiumId: 'condo-palacio-real',
    normType: 'ESTANQUEIDADE_GAS',
    title: 'Laudo de Estanqueidade da Rede de Gás Canalizado (GN/GLP)',
    code: 'NBR 15526 / NBR 15358 / IT-28 CBMET',
    legalBasis: 'Ensaio pneumático com manômetro diferencial garantindo ausência de vazamentos nas prumadas.',
    validityDate: '2027-04-18',
    status: 'CONFORME',
    certNumber: 'ESTANQ-GAS-2025-110',
    artNumber: 'ART-GAS-881920',
    responsibleEngineer: 'Eng. Mecânico Duncan / Mentor',
    creaRrt: 'CREA-ET 506112998',
    inspectionFrequency: 'ANUAL',
    lastInspection: '2025-04-18',
    nextInspection: '2027-04-18',
  }
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 'part-rolamento-skf',
    code: 'PEC-ROL-6308',
    name: 'Rolamento SKF 6308 2RS C3 de Eternium Reforçado',
    category: 'HIDRAULICA',
    quantity: 8,
    minQuantity: 4,
    unit: 'unid',
    unitCost: 145.0,
    supplier: 'Distribuidora Eternia Peças & Tecnologia',
    location: 'Prateleira H-02 (Arsenal Central de Duncan)',
    lastRestock: '2026-07-10',
  },
  {
    id: 'part-filtro-manta-g4',
    code: 'PEC-FLT-G4',
    name: 'Manta Filtrante Sintética G4 de Fibra de Eternia (PMOC Climatização)',
    category: 'CLIMATIZACAO',
    quantity: 32,
    minQuantity: 15,
    unit: 'm²',
    unitCost: 38.0,
    supplier: 'Filtros AirTech Eternia',
    location: 'Prateleira C-01 (Torre de Grayskull)',
    lastRestock: '2026-08-01',
  },
  {
    id: 'part-selo-mecanico-viton',
    code: 'PEC-SLO-125',
    name: 'Selo Mecânico 1.1/4" Viton / Carbeto de Silício Duncan',
    category: 'HIDRAULICA',
    quantity: 5,
    minQuantity: 2,
    unit: 'unid',
    unitCost: 220.0,
    supplier: 'Schneider Bombas & Vedações Eternia',
    location: 'Prateleira H-03',
    lastRestock: '2026-06-15',
  },
  {
    id: 'part-bateria-12v-gerador',
    code: 'PEC-BAT-100AH',
    name: 'Bateria Chumbo-Ácido & Plasma 12V 100Ah Selada (Gerador Standby Grayskull)',
    category: 'GERADORES',
    quantity: 3,
    minQuantity: 2,
    unit: 'unid',
    unitCost: 650.0,
    supplier: 'Moura Acumuladores Industriais',
    location: 'Bancada Elétrica E-01 (Oficina Duncan)',
    lastRestock: '2026-05-20',
  },
  {
    id: 'part-lampada-led-emergencia',
    code: 'PEC-ILU-BLOCO',
    name: 'Bloco Autônomo de Iluminação de Emergência LED 30W (AVCB)',
    category: 'INCENDIO_AVCB',
    quantity: 12,
    minQuantity: 6,
    unit: 'unid',
    unitCost: 85.0,
    supplier: 'SegurFire Equipamentos de Eternia',
    location: 'Prateleira I-02',
    lastRestock: '2026-08-10',
  },
  {
    id: 'part-disjuntor-tripolar-50a',
    code: 'PEC-DIS-3P50',
    name: 'Disjuntor Caixa Moldada Tripolar 50A 25kA (Proteção NR-10 / Plasma)',
    category: 'ELETRICA_SPDA',
    quantity: 4,
    minQuantity: 2,
    unit: 'unid',
    unitCost: 195.0,
    supplier: 'Schneider Electric Brasil',
    location: 'Armário Elétrico E-03',
    lastRestock: '2026-07-22',
  }
];

export const INITIAL_FINANCIAL: FinancialRecord[] = [
  {
    id: 'fin-001',
    condominiumId: 'condo-grayskull',
    title: 'Contrato de Manutenção Preventiva & PMOC Castelo de Grayskull',
    type: 'CONTRATO_MENSAL',
    amount: 14850.0,
    dueDate: '2026-09-10',
    status: 'PENDENTE',
    invoiceNumber: 'NF-2026-09-0881',
  },
  {
    id: 'fin-002',
    condominiumId: 'condo-grayskull',
    title: 'Peças Utilizadas: Rolamento SKF Eternium e Manta G4',
    type: 'PECAS_ESTOQUE',
    amount: 297.0,
    dueDate: '2026-09-15',
    status: 'PENDENTE',
    invoiceNumber: 'FAT-PECAS-2026-88',
  },
  {
    id: 'fin-003',
    condominiumId: 'condo-grayskull',
    title: 'Mensalidade Manutenção Preventiva Facilities (Agosto/2026)',
    type: 'CONTRATO_MENSAL',
    amount: 14850.0,
    dueDate: '2026-08-10',
    paidDate: '2026-08-08',
    status: 'PAGO',
    invoiceNumber: 'NF-2026-08-0740',
  },
  {
    id: 'fin-004',
    condominiumId: 'condo-palacio-real',
    title: 'Contrato Manutenção Predial 4.0 & Gêmeo Digital Palácio Real',
    type: 'CONTRATO_MENSAL',
    amount: 28400.0,
    dueDate: '2026-09-05',
    status: 'PENDENTE',
    invoiceNumber: 'NF-2026-09-0882',
  }
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-01',
    timestamp: '2026-09-01T17:30:00Z',
    userId: 'user-tecnico',
    userName: 'Duncan / Mentor (Man-At-Arms)',
    role: 'TECNICO',
    action: 'INICIO_EXECUCAO_OS',
    target: 'OS-2026-089',
    details: 'Duncan iniciou trabalho em campo na Moto-Bomba de Grayskull (Subsolo 2) com checklist NR-10/LOTO.',
  },
  {
    id: 'log-02',
    timestamp: '2026-09-01T17:25:00Z',
    userId: 'system-iot',
    userName: 'Sistema Telemetria IoT 4.0',
    role: 'ADMIN',
    action: 'DISPARO_ALERTA_PREDITIVO',
    target: 'HID-BMB-001',
    details: 'Vibração RMS excedeu threshold seguro (4.82 mm/s > 4.5 mm/s). OS de emergência gerada.',
  },
  {
    id: 'log-03',
    timestamp: '2026-09-01T16:15:00Z',
    userId: 'user-admin',
    userName: 'Eng. Príncipe Adam (He-Man)',
    role: 'ADMIN',
    action: 'APROVACAO_LAUDO_PMOC',
    target: 'PMOC-2026-ET-8821',
    details: 'ART registrada no CREA-ET e laudo emitido com conformidade legal 100%.',
  }
];

export const INITIAL_KPIS: ReliabilityKPIs = {
  mttrHours: 2.1,
  mtbfDays: 48.5,
  pmocComplianceRate: 98.4,
  avcbComplianceRate: 100.0,
  slaAdherenceRate: 97.2,
  totalMonitoredSensors: 34,
  criticalAlertsCount: 1,
  activeWorkOrders: 4,
  completedThisMonth: 18,
};

// Aliases for component compatibility
export const MOCK_USERS = INITIAL_USERS;
export const MOCK_CONDOMINIUMS = INITIAL_CONDOMINIUMS;
export const MOCK_ASSETS = INITIAL_ASSETS;
export const MOCK_WORK_ORDERS = INITIAL_WORK_ORDERS;
export const MOCK_NORMATIVES = INITIAL_NORMATIVES;
export const MOCK_INVENTORY = INITIAL_INVENTORY;
export const MOCK_INVOICES = INITIAL_FINANCIAL;
export const MOCK_FINANCIAL = INITIAL_FINANCIAL;
export const MOCK_KPI = INITIAL_KPIS;

